

 POST  http://localhost:8000/
Content-Type: application/json

{
   "username": "james",
   "password": "smelly"
}

GET  http://localhost:8000/photos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiamFtZXMiLCJwYXNzd29yZCI6InNtZWxseSJ9LCJpYXQiOjE1ODk1NTQ2NTJ9.7IgmHUC4ztrlfnPxIddHXFGPSNgZ-8BLy7Wb43gJ6Ko