service: my-serverless-app

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: production
  region: eu-west-2

functions:
  app:
    handler: index.handler
    # package:
    #   include:
    #     - index.js
    #     - lib/**
    #     - node_modules/**
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-offline
